bases:
  - ../../base
configMapGenerator:
- name: springboot-redis-pattern-config
  behavior: merge
  files:
    # overlay에서는 이 property 파일을 수정하여 
    # base에 설정된 값을 overwrite 할 수 있다. 
    - application-overlay.yaml